#
#JDBC props
#
app:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/employee_directory?useSSL=false    username: springstudent
    password: springstudent

#
spring:  data:    jpa:      entity:
        packages-to-scan: com.thymeleafdemo.thymeleafdemo.entity
      repository:
        packages-to-scan: com.thymeleafdemo.thymeleafdemo.repository
 
           
#
#Security props
#
security:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/spring_security_demo_bcrypt?useSSL=false
    username: springstudent
    password: springstudent
  